# Generated by Django 3.1.3 on 2020-11-20 22:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20201120_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='date_hired',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 20, 22, 47, 29, 502802, tzinfo=utc)),
        ),
    ]
