# Generated by Django 3.1.3 on 2020-11-21 18:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20201120_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='date_hired',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 21, 18, 5, 28, 869964, tzinfo=utc)),
        ),
    ]
