# Generated by Django 3.1.3 on 2020-11-21 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_auto_20201121_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='date_hired',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 21, 19, 27, 3, 845519, tzinfo=utc)),
        ),
    ]
